// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKiTCrQcivGPVjbgnGj8sVE0GdNxUTtY',
    appId: '1:94550324733:web:36c3847bf6edd0a244d594',
    messagingSenderId: '94550324733',
    projectId: 'erudite-descent-448911-h5',
    authDomain: 'erudite-descent-448911-h5.firebaseapp.com',
    storageBucket: 'erudite-descent-448911-h5.firebasestorage.app',
    measurementId: 'G-HF6ZN0R4B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-3f6e4Ijw6TYAb-uLBO9P9jY1OZ4D2w',
    appId: '1:94550324733:android:87b169ea8231436a44d594',
    messagingSenderId: '94550324733',
    projectId: 'erudite-descent-448911-h5',
    storageBucket: 'erudite-descent-448911-h5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOYxtKRNIm0sNtQVUfPuDPeiPsfIlBYPQ',
    appId: '1:94550324733:ios:298701215e82135944d594',
    messagingSenderId: '94550324733',
    projectId: 'erudite-descent-448911-h5',
    storageBucket: 'erudite-descent-448911-h5.firebasestorage.app',
    androidClientId: '94550324733-lagucicn2rsskfrigsfnbg9t1o4ag4th.apps.googleusercontent.com',
    iosClientId: '94550324733-n8f250h0c9cvp81acqdopip88jpcuej5.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSecondbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNKiTCrQcivGPVjbgnGj8sVE0GdNxUTtY',
    appId: '1:94550324733:web:3c63b14d0ba0648c44d594',
    messagingSenderId: '94550324733',
    projectId: 'erudite-descent-448911-h5',
    authDomain: 'erudite-descent-448911-h5.firebaseapp.com',
    storageBucket: 'erudite-descent-448911-h5.firebasestorage.app',
    measurementId: 'G-12PY586ZME',
  );

}